### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by buro9** [rjohnsondev/go-safe-browsing-api#10]
I'd like to use this to check outbound links on some forums I run.

Could you add a licence to the project please so that I know that it is fine to do so.

**Comment by rjohnsondev** [comment]
Sure, the code is licensed under the 2-clause BSD license http://opensource.org/licenses/BSD-2-Clause

This is in the source headers, will add it to the project.

**Comment by buro9** [comment]
Thanks, this is much appreciated. I tend not to look at source code for a project if I don't know in advance that the license is somewhat permissive. Overly cautious perhaps, but the joys of a security background.

**Comment by rjohnsondev** [comment]
fixed by https://github.com/rjohnsondev/go-safe-browsing-api/commit/69527a6fa6487b18861ca4cbc9250727ac1ba28e
