### ISSUE TITLE
can full hashes be downloaded in bulk, in advance?

### ISSUE THREAD

**Issue by glycerine** [rjohnsondev/go-safe-browsing-api#6]
Hi Richard,

Thank you for this really useful go binding! It is really nice.

I'm trying out the v3 adaption that github.com/kgilonne/go-safe-browsing-api provides.

One problem: I get a ton of false positives from MightBeListed(), and IsListed() is too slow.  Is it possible to pull down the full hashes every 1800 minutes (or the update frequency that google requests), and to otherwise remain offline while having accurate (full) hash matching?

Thanks!
Jason

**Comment by rjohnsondev** [comment]
Hey Jason,

Glad you find it useful; I'll be looking to merge in the v3 fork at some point when I have time.

Interesting thought, while I can't see this being explicitly forbidden in a quick review of the docs, it isn't really intended behaviour from google's standpoint as outlined in the spec.  Google is also quite explicit about full hashes not returning a positive for the IsListed unless there has been an update in the last 45 mins.

From a practicality point of view, there seem to be around 300,000 prefix hashes around at any one time.  The full length lookup call is designed to allow for a couple of hash lookups at once, but I'd be confident there would be a limit to the volume allowed with a single request.  If however you managed to get a hundred prefix responses each request you could feasibly get the full DB with 3,000 requests.  I would expect you to hit the backoff behaviour requests at some point trying to do that however.  I'm also unsure on how much data this would end up being, I would speculate that it's a lot ;).  (This is all assuming the new protocol follows the same basic behaviour as v2)

All up, I'm not completely sure what you are trying to do, however unless you are running a list of URLs with a really, really high bad-URL hit ratio I think you would still be better off using MightBeListed, letting the matches trickle in through an async IsListed call for interesting matches over time, then re-running the full list again.  Some hacking to the library here https://github.com/rjohnsondev/go-safe-browsing-api/blob/master/safebrowsing.go#L364 will allow you to extend the 45 mins to something longer if it is taking more than say 30 mins to retrieve your full hashes.

Thanks,

Richard

**Comment by glycerine** [comment]
Thanks for your thoughts Richard.  The primary problem I'm having is that the number of links I want to scan (6K-8K per second) is just too much for a network roundtrip to google to keep up.  I've asked on the google group for the api, but it doesn't seem to be attended. I may try to email the original devs directly for their advice.

I don't mind updating every 30 minutes at all, since that can be done in the background in parallel. But with IsListed() now I'm only getting 10-20 links scanned per second, even with using MightBeListed() first--there are just that many collisions in the 32-bit hash prefix space.

Anyway. I appreciate your suggestions. I'll let you know if I figure out a solution.

**Comment by glycerine** [comment]
Hi Richard,

I consulted with one of the safe-browsing-api developers, and he suggested a batching strategy [below]. Is this viable? Could you advise on/suggest how to impliment such batching?

Thanks!

Jason



~~~
---------- Forwarded message ----------
From: Noé Lutz
Date: Wed, Jan 28, 2015 at 4:42 PM
To: Jason

Hi Jason,
Even at 10K links per second you should only see an estimated 1-2 hits per 
second.  That's assuming the database contains 500K entries.  Is that roughly 
what you're seeing?  Hash lookups are extremely efficient and they can also 
be batched.  Can you somehow put matching URLs in a separate queue and 
then batch hash server requests to our frontends?

There is really no good way to download the entire list of full hashes.  You 
could (technically) issue a hash server request whenever you get an update 
to pre-lengthen all the hash prefixes that you just got in an update.  I don't 
think this would violate our policy but it would certainly not be the usual way 
of using the protocol.

Hope that helps.
noe.
~~~

**Comment by rjohnsondev** [comment]
Yup, the full-length hash lookup is here https://github.com/rjohnsondev/go-safe-browsing-api/blob/master/safebrowsing.go#L453 this is usually called with the generated hashes for a matching URL.

You would want to modify the `queryUrl` call to return the partial hash matches for a URL early, or even throw them onto a channel here https://github.com/rjohnsondev/go-safe-browsing-api/blob/master/safebrowsing.go#L432 where you can buffer until you have a desired number, then drain them to `requestFullHashes`.

**Comment by glycerine** [comment]
Cool, I'll give that a try. Thanks Richard.
